pipeline:
  name: muletest
  identifier: muletest
  projectIdentifier: FM_Sandbox
  orgIdentifier: SE_Sandbox
  tags: {}
  properties:
    ci:
      codebase:
        repoName: mulesoftpipeline
        build: <+input>
  stages:
    - stage:
        identifier: build
        type: CI
        name: build
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Background
                  name: Background_2
                  identifier: Background_2
                  spec:
                    connectorRef: harnessdockerregistry2
                    image: mysql:8.1.0
                    shell: Sh
                    envVariables:
                      MYSQL_ROOT_PASSWORD: my-secret-pw
                      MYSQL_DATABASE: legacy
                    portBindings:
                      "3306": "3306"
                    runAsUser: "0"
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: |
                      sleep 60
                      #telnet localhost 3306
                      #service mysql start
                      #systemctl status mysql
                      #sleep 20
                      #systemctl status mysql
                      #sudo systemctl start mysql
                      #mysql -h localhost -p my-secret-pw -P 3306 -D legacy
                      mysql -h Background_2 -p my-secret-pw -u root -P 3306 -D legacy
                    privileged: true
                    runAsUser: "0"
        description: ""
